
type Video {
  name: String!
  location: String!
  city: String
  country: String
  continent: String
  latitude: Int
  longitude: Int
  description: String
  image: String
  date: String
  video_url: String
  video_id: String
  video_host: String
  credit: String
  owner: User!
  createdAt: Date
  updatedAt: Date
}



type User {
  email: String! @unique
  videos: [Video!] @relation
  firstName: String
  lastName: String
  createdAt: Date
  updatedAt: Date
}

type Query {
  allVideos: [Video!]
  findVideosByCountry(country: String!): [Video!]
  findVideosByCity(city: String!): [Video!]
  findVideosByContinent(continent: String!): [Video!]
}

