type Todo {
  task: String!
  completed: Boolean!
  owner: User!
}

type Video {
  name: String!
  location: String!
  city: String
  country: String
  latitude: Int
  longitude: Int
  description: String
  image: String
  date: String
  video_url: String
  video_id: String
  video_host: String
  credit: String
  owner: User!
}

type User {
  email: String! @unique
  todos: [Todo!] @relation
  videos: [Video!] @relation
}

type Query {
  allTodos: [Todo!]
  allVideos: [Video!]
}

